parameters:
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: default

        connections:
            default:
                driver: pdo_pgsql
                charset: utf8
                server_version: 13
                url: '%env(DATABASE_URL)%'

    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: default

        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
