monolog:
    handlers:
        main:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels:
                - "!event"
                - "!doctrine"
                - "!router"
                - "!request"

        deprecation:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"

        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            channels: [ "php" ]

        console:
            type: console
            process_psr_3_messages: false
            channels:
                - "!event"
                - "!doctrine"
                - "!console"
